online_market/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
]

online_market/online_market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from products import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_market/products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('home/', views.home, name="home"),
    #
    path('', views.products, name='products'),
    path('<int:pk>/', views.product_detail, name='product_detail'),
    path('<int:pk>', views.like, name='like'),
    #
    path('create', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    #
]

online_market/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.users, name='users'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

online_market/products/models.py
from django.db import models
from django.conf import settings

class Product(models.Model):
    name = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(
        upload_to='images/',
        blank=True,
        null=True,
    )
    
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="products",
    )

    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_products"
    )
    
    def __str__(self):
        return self.name

online_market/products/forms.py
from django import forms
from products.models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        exclude = ("author", "like_users")

online_market/products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product
from django.views.decorators.http import require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from .forms import ProductForm

def home(request):
    return render(request, 'products/home.html')

def products(request):
    products = Product.objects.all().order_by("-pk")
    context = {
        "products": products
    }
    return render(request, "products/products.html", context)

def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        "product": product
    }
    return render(request, "products/product_detail.html", context)

@require_POST
def like(request, pk):
    if request.user.is_authenticated:
        product = get_object_or_404(Product, pk=pk)
        if product.like_users.filter(pk=request.user.pk).exists():
            product.like_users.remove(request.user)
        else:
            product.like_users.add(request.user)
    else:
        return redirect("accounts:login")
    
    return redirect("products:products")

@login_required
def create(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)  # 데이터가 바인딩된(값이 채워진) Form
        if form.is_valid():  # Form이 유효하다면 데이터를 저장하고 다른 곳으로 redirect
            product = form.save(commit=False)
            product.author = request.user
            product.save()
            return redirect("products:product_detail", product.pk)
    # 기존 new 함수 부분
    else:
        form = ProductForm()

    context = {"form": form}
    return render(request, "products/create.html", context)

@login_required
@require_http_methods(["GET", "POST"])
def update(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if product.author == request.user:
        if request.method == "POST":    # instance라는 속성에 값이 있으면 instance 수정
            form = ProductForm(request.POST, instance=product)
            if form.is_valid():
                product = form.save()
                return redirect("products:product_detail", product.pk)
        else:   # 없으면 새로 생성
            form = ProductForm(instance=product)
    else:
        return redirect("products:products")

    context = {
        "form": form,
        "product": product,
    }
    return render(request, "products/update.html", context)

@require_POST
def delete(request, pk):
    if request.user.is_authenticated:
        product = get_object_or_404(Product, pk=pk)
        if product.author == request.user:
            product.delete()
    return redirect("products:products")

online_market/templates/products/create.html
{% extends "base.html" %}

{% block content %}
    <h1>새 물품 등록</h1>

    <form action="{% url 'products:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}  <!-- form은 p 태그로 표현 -->
        <button type="submit">저장</button>
    </form>

    <br/>
    <a href="{% url 'products:products' %}">목록 보기</a>
{% endblock content %}

online_market/templates/products/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to Seok's Market!!</h1>

    <nav>
        <ul>
            <li><a href="{% url 'products:products' %}">물품 목록</a></li>
            <li><a href="{% url 'users:users' %}">User's profile</a></li>
        </ul>
    </nav>
{% endblock content %}

online_market/templates/products/product_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>상품 정보</h1>
    <p>상품명: {{ product.name }}</p>
    <p>게시자: {{ product.author.username }}</p>

    {% if product.image %}
        <img src="{{ product.image.url }}">
    {% endif %}

    <p>상품 설명: {{ product.content }}</p>
    <p>작성 일시: {{ product.created_at }}</p>
    <p>수정 일시: {{ product.updated_at }}</p>

    <br/>
    <br/>

    <a href="{% url 'products:products' %}">
        <button>전체 상품 목록보기</button>
    </a>
    <br/>

    {% if user == product.author %}
        <a href="{% url 'products:update' product.pk %}">
            <button>글수정</button>
        </a>
        <br/>
        <form action="{% url 'products:delete' product.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="글삭제">
        </form>
    {% endif %}
    
{% endblock content %}

online_market/templates/products/products.html
{% extends "base.html" %}

{% block content %}
    <h1>상품 목록</h1>

    {% if request.user.is_authenticated %}
        <br/>
        <a href="{% url 'products:create' %}">
            <button>새 상품 등록</button>
        </a>
    {% else %}
        <br/>
        <a href="{% url 'accounts:login' %}">
            <button>물품 등록을 위한 로그인!</button>
        </a>
    {% endif %}
    
    <hr/>
    {% for product in products %}
        <!-- product_detail에 필요한 인자인 product.pk를 같이 넘겨줌 -->
        <a href="{% url 'products:product_detail' product.pk %}">
            <p>[ {{ product.pk }} ] {{ product.name }} - {{ product.author }}</p>
        </a>
        {% if request.user.is_authenticated %}
            <form action="{% url 'products:like' product.pk %}" method="POST">
                {% csrf_token %}
                {% if user in product.like_users.all %}
                    <button>찜 해제</button> 
                {% else %}
                    <button>찜 하기</button> 
                {% endif %}
        {% endif %}
        </form>
        <br/>
        <hr/>
    {% endfor %}
    <a href="{% url 'products:home' %}">
        <button>홈으로 돌아가기</button>
    </a>
{% endblock content %}

online_market/templates/products/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>게시물 수정</h1>

    <form action="{% url 'products:update' product.pk %}" method="POST">
        {% csrf_token %}
        <label for="title">제목</label>
        {{ form.as_p }}
        
        <button type="submit">수정</button>
    </form>
    <br/>

    <a href="{% url 'products:product_detail' product.pk %}">이전으로</a>
{% endblock content %}