online_market/online_market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from products import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_market/products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('home/', views.home, name="home"),
    #
    path('', views.products, name='products'),
    path('<int:pk>/', views.product_detail, name='product_detail'),
    path('<int:pk>', views.like, name='like'),
    #
    path('create', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    #
]

online_market/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.users, name='users'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

online_market/users/models.py
from django.db import models

# Create your models here.

online_market/users/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from accounts.models import User
from products.models import Product

def users(request):
    users = User.objects.all().order_by("id")
    context = {"users": users}
    return render(request, "users/users.html", context)

def profile(request, username):
    member = get_object_or_404(get_user_model(), username=username)
    products = Product.objects.filter(author_id=member.pk)
    like_products = Product.objects.filter(like_users=member.pk)
    context = {
        "member": member,
        "products": products,
        "like_products": like_products,
    }
    return render(request, "users/profile.html", context)

@require_POST
def follow(request, user_id):
    # request.user == "현재 로그인한 사람"
	# member == "누군가의 프로필"
    if request.user.is_authenticated:
        member = get_object_or_404(get_user_model(), pk=user_id)
        if request.user != member:  # 자기 자신을 팔로우하는 경우 제외 
            if request.user in member.followers.all():
                member.followers.remove(request.user)
            else:
                member.followers.add(request.user)
        return redirect("users:profile", member.username)
    return redirect("accounts:login")

online_market/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>유저 정보 페이지</h1>

    <div>
        <h2>ID : {{ member.username }}</h2>
        <p>
            가입일: {{ member.date_joined|date:"Y-m-d" }}<br>
            팔로워 : {{ member.followers.count }}명
            팔로잉 : {{ member.following.count }}명
        </p>
    </div>
    <hr/>

    <h3>등록 물품: {{ products|length }}</h3>
    {% for product in products %}
        <ul>
            <li>
                <a href="{% url 'products:product_detail' product.pk %}">
                    <p>[{{ forloop.counter }}] {{ product.name }}</p>
                </a>
            </li>
        </ul>
    {% endfor %}
    <br/>
    <hr/>

    <h3>찜 목록: {{ like_products|length }}개</h3>
    {% for like_product in like_products %}
        <ul>
            <li>
                <a href="{% url 'products:product_detail' like_product.pk %}">
                    <p>{{ like_product.name }}</p>
                </a>
            </li>
        </ul>
    {% endfor %}
    <br/>
    <hr/>

    {% if request.user != member %}
        <div>
            <form action="{% url 'users:follow' member.pk %}" method="POST">
                {% csrf_token %}
                {% if request.user in member.followers.all %}
                    <button type="submit">Unfollow</button>
                {% else %}
                    <button type="submit">Follow</button>
                {% endif %}
            </form>
        </div>
    {% endif %}

    <a href="{% url 'users:users' %}">
        <button>유저 목록으로 돌아가기</button>
    </a>
    <br/>
    <a href="{% url 'products:home' %}">
        <button>홈으로 돌아가기</button>
    </a>
{% endblock content %}