online_market/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
]

online_market/online_market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from products import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_market/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.users, name='users'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

online_market/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    following = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )  # symmetrical=True이면 누군가를 팔로우 하자마자 맞팔이 됨. default 값은 True 

online_market/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from django.urls import reverse

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
        )

    def __init__(self, *args, **kwargs):    # 비밀번호 수정 경로 커스텀 할 수 있게 UserChangeForm의 생성자 메서드를 오버라이딩
        super().__init__(*args, **kwargs)
        if self.fields.get("password"):
            password_help_text = (
                "You can change the password " '<a href="{}">here</a>.'
            ).format(f"{reverse('accounts:change_password')}")  # reverse: url_name으로부터 url을 찾아가는 함수
            self.fields["password"].help_text = password_help_text

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()    # 현재 활성화된 user model, User를 model로 사용
        fields = UserCreationForm.Meta.fields

online_market/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
)
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import (
    require_POST,
    require_http_methods,
)
from django.contrib.auth.decorators import login_required
from .forms import CustomUserChangeForm, CustomUserCreationForm

@require_http_methods(["GET", "POST"])  # GET, POST 요청받을 때만 login 실행
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())    # 로그인
            next_url = request.GET.get("next") or "home"    # 로그인 성공하면 이동하려던 곳, 실패하면 홈 이동
            return redirect(next_url)
    else:        
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "accounts/login.html", context)

@require_POST   # POST 요청 시에만 logout 실행
def logout(request):
    if request.user.is_authenticated:   # user가 로그인이 된 상태라면
        auth_logout(request)    # 로그아웃
    return redirect("home")

@require_http_methods(["GET", "POST"])
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()  # 새유저 정보 저장
            auth_login(request, user)   # 가입함과 동시에 로그인
            return redirect("home")
    else:
        form = CustomUserCreationForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)

@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()   # 회원 탈퇴
        auth_logout(request)    # 세션 지우기
    return redirect("home")

@require_http_methods(["GET", "POST"])
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("home")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {"form": form}
    return render(request, "accounts/update.html", context)

@login_required
@require_http_methods(["GET", "POST"])
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("home")
    else:
        form = PasswordChangeForm(request.user)
    context = {"form": form}
    return render(request, "accounts/change_password.html", context)

online_market/templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}
    <h1>비밀번호 변경</h1>

    <form action="{% url 'accounts:change_password' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">비밀번호 변경</button>
    </form>
{% endblock content %}

online_market/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
    <h1>로그인</h1>

    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">로그인</button>
    </form>

{% endblock content %}

online_market/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
    <h1>회원가입</h1>
    <form action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">회원가입</button>
    </form>

{% endblock %}

online_market/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>회원 정보 수정</h1>

    <form action="{% url 'accounts:update' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">수정</button>
    </form>

    <form action="{% url 'accounts:delete' %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="회원탈퇴"></input>
    </form>
{% endblock content %}